site_name: Turing Community Documentation
theme:
  name: material
  palette:
    primary: grey
    accent: cyan
    icon:
      repo: fontawesome/brands/github
  font: false
repo_url: https://github.com/turing-machines/turing-docs
repo_name: turing-machines/turing-docs
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
plugins:
  - search
  - git-revision-date
nav:
   - Home: 'index.md'
   - FAQ: 'FAQ/index.md'

